# Generated by Django 3.2.9 on 2021-11-20 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_talk_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talk_category', to='website.category', verbose_name='Categoría'),
        ),
    ]
