# Generated by Django 3.2.9 on 2021-11-21 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_talk_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talk',
            name='author',
        ),
        migrations.AddField(
            model_name='talk',
            name='speaker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.profile', verbose_name='Ponente'),
        ),
    ]
